name: modest_pagination
description: Attempt at modularizing my own pagination
version: 0.0.1
homepage: https://github.com/iamngoni/modest-pagination

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  handy_extensions:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: